const pistols = [
    {
        name: "P226",
        ammo: 5, magazines: 4,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/pistols/p226.png",
        damage: 85,
        rateOfFire: 55,
        range: 49,
        accuracy: 40,
        bulletSpeed: 70,
        mobility: 98
    },
    {
        name: "P08",
        ammo: 7, magazines: 5,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/pistols/p08.png",
        damage: 85,
        rateOfFire: 65,
        range: 48,
        accuracy: 57,
        bulletSpeed: 83,
        mobility: 98
    },
    {
        name: "Golden Desert Eagle",
        ammo: 7, magazines: 0,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/pistols/golden_deagle.png",
        damage: 86,
        rateOfFire: 17,
        range: 49,
        accuracy: 28,
        bulletSpeed: 66,
        mobility: 94
    },
    {
        name: "Desert Eagle",
        ammo: 5, magazines: 4,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/pistols/deagle.png",
        damage: 90,
        rateOfFire: 20,
        range: 53,
        accuracy: 30,
        bulletSpeed: 80,
        mobility: 98
    },
    {
        name: "Glock 18C",
        ammo: 13, magazines: 4,
        duration: "Permanent",
        price: 168.00,
        image: "src/imagens/pistols/glock18c.png",
        damage: 60,
        rateOfFire: 70,
        range: 50,
        accuracy: 29,
        bulletSpeed: 70,
        mobility: 98
    },
    {
        name: "Beretta M92",
        ammo: 13, magazines: 4,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/pistols/m92.png",
        damage: 76,
        rateOfFire: 51,
        range: 62,
        accuracy: 55,
        bulletSpeed: 72,
        mobility: 98
    },
    {
        name: "M1911",
        ammo: 9, magazines: 5,
        duration: "Permanent",
        price: 168.00,
        image: "src/imagens/pistols/m1911.png",
        damage: 81,
        rateOfFire: 49,
        range: 60,
        accuracy: 55,
        bulletSpeed: 75,
        mobility: 98
    },
    {
        name: ".44 Magnum",
        ammo: 5, magazines: 5,
        duration: "Permanent",
        price: 168.00,
        image: "src/imagens/pistols/magnum44.png",
        damage: 90,
        rateOfFire: 51,
        range: 62,
        accuracy: 55,
        bulletSpeed: 72,
        mobility: 98
    }
];
