const rifles = [
    {
        name: "G36K (Aurora)",
        ammo: 30, magazines: 5,
        duration: "Permanent",
        price: "Lottery - Limited",
        image: "src/imagens/rifles/g36k_aurora.png",
        damage: 84,
        rateOfFire: 70,
        range: 71,
        accuracy: 74,
        bulletSpeed: 75,
        mobility: 94
    },
    {
        name: "F2000 Antitank-SS",
        ammo: 30, magazines: 5,
        duration: "Permanent",
        price: "Lottery - Limited",
        image: "src/imagens/rifles/f2000_antitank.png",
        damage: 72,
        rateOfFire: 80,
        range: 74,
        accuracy: 80,
        bulletSpeed: 74,
        mobility: 94
    },
    {
        name: "M4A1-SS (Tradeable)",
        ammo: 35, magazines: 7,
        duration: "Permanent",
        price: "Lottery - Limited",
        image: "src/imagens/rifles/m4a1.png",
        damage: 79,
        rateOfFire: 75,
        range: 72,
        accuracy: 74,
        bulletSpeed: 85,
        mobility: 90
    },
    {
        name: "LegandCore-Power-L50",
        ammo: 50, magazines: 7,
        duration: "Permanent",
        price: "Papa Boss Box",
        image: "src/imagens/rifles/lcp.png",
        damage: 86,
        rateOfFire: 65,
        range: 70,
        accuracy: 55,
        bulletSpeed: 75,
        mobility: 90
    },
    {
        name: "SR15",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 256.00,
        image: "src/imagens/rifles/sr15.png",
        damage: 80,
        rateOfFire: 70,
        range: 80,
        accuracy: 81,
        bulletSpeed: 73,
        mobility: 94
    },
    {
        name: "XM8",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/rifles/xm8.png",
        damage: 74,
        rateOfFire: 70,
        range: 78,
        accuracy: 80,
        bulletSpeed: 90,
        mobility: 94
    },
    {
        name: "Golden G3A3",
        ammo: 25, magazines: 5,
        duration: "Permanent",
        price: 238.00,
        image: "src/imagens/rifles/golden_g3a3.png",
        damage: 79,
        rateOfFire: 70,
        range: 80,
        accuracy: 70,
        bulletSpeed: 68,
        mobility: 94
    },
    {
        name: "Arctic G3A3",
        ammo: 25, magazines: 5,
        duration: "Permanent",
        price: 238.00,
        image: "src/imagens/rifles/arctic_g3a3.png",
        damage: 79,
        rateOfFire: 70,
        range: 80,
        accuracy: 70,
        bulletSpeed: 68,
        mobility: 94
    },
    {
        name: "XM8 (Tiger)",
        ammo: 30, magazines: 3,
        duration: "Permanent",
        price: 200.00,
        image: "src/imagens/rifles/xm8_tiger.png",
        damage: 74,
        rateOfFire: 70,
        range: 90,
        accuracy: 70,
        bulletSpeed: 90,
        mobility: 94
    },
    {
        name: "XM8 (Mission)",
        ammo: 30, magazines: 3,
        duration: "Permanent",
        price: 200.00,
        image: "src/imagens/rifles/xm8_mission.png",
        damage: 74,
        rateOfFire: 75,
        range: 78,
        accuracy: 80,
        bulletSpeed: 80,
        mobility: 94
    },
    {
        name: "XM8 (Alien)",
        ammo: 30, magazines: 3,
        duration: "Permanent",
        price: 200.00,
        image: "src/imagens/rifles/xm8_alien.png",
        damage: 74,
        rateOfFire: 70,
        range: 78,
        accuracy: 80,
        bulletSpeed: 90,
        mobility: 94
    },
    {
        name: "Golden AK47s (Tradeable)",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 66.00,
        image: "src/imagens/rifles/golden_ak.png",
        damage: 90,
        rateOfFire: 45,
        range: 50,
        accuracy: 38,
        bulletSpeed: 62,
        mobility: 90
    },
    {
        name: "Galil",
        ammo: 35, magazines: 6,
        duration: "Permanent",
        price: 110.00,
        image: "src/imagens/rifles/galil.png",
        damage: 70,
        rateOfFire: 85,
        range: 60,
        accuracy: 70,
        bulletSpeed: 70,
        mobility: 94
    },
    {
        name: "M4 Special",
        ammo: 30, magazines: 5,
        duration: "30 Days",
        price: 60.00,
        image: "src/imagens/rifles/m4spe.png",
        damage: 84,
        rateOfFire: 70,
        range: 65,
        accuracy: 78,
        bulletSpeed: 73,
        mobility: 94
    },
    {
        name: "AN94",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/rifles/an94.png",
        damage: 81,
        rateOfFire: 70,
        range: 75,
        accuracy: 82,
        bulletSpeed: 66,
        mobility: 94
    },
    {
        name: "AK47",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 98.00,
        image: "src/imagens/rifles/ak47.png",
        damage: 90,
        rateOfFire: 46,
        range: 54,
        accuracy: 40,
        bulletSpeed: 62,
        mobility: 94
    },
    {
        name: "M4",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/rifles/m4.png",
        damage: 70,
        rateOfFire: 70,
        range: 65,
        accuracy: 75,
        bulletSpeed: 72,
        mobility: 94
    },
    {
        name: "SAM-R",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 158.00,
        image: "src/imagens/rifles/sam_r.png",
        damage: 73,
        rateOfFire: 73,
        range: 80,
        accuracy: 78,
        bulletSpeed: 73,
        mobility: 94
    },
    {
        name: "AK-47S",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/rifles/ak47s.png",
        damage: 78,
        rateOfFire: 85,
        range: 53,
        accuracy: 44,
        bulletSpeed: 67,
        mobility: 94
    },
    {
        name: "G3A3",
        ammo: 25, magazines: 5,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/rifles/g3a3.png",
        damage: 79,
        rateOfFire: 70,
        range: 80,
        accuracy: 70,
        bulletSpeed: 68,
        mobility: 94
    },
    {
        name: "FAL",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 168.00,
        image: "src/imagens/rifles/fal.png",
        damage: 76,
        rateOfFire: 66,
        range: 80,
        accuracy: 74,
        bulletSpeed: 70,
        mobility: 94
    },
    {
        name: "MP5A4",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 169.00,
        image: "src/imagens/rifles/mp5a4.png",
        damage: 69,
        rateOfFire: 88,
        range: 51,
        accuracy: 43,
        bulletSpeed: 82,
        mobility: 94
    },
    {
        name: "AK47 GL",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/rifles/ak47_gl.png",
        damage: 90,
        rateOfFire: 46,
        range: 54,
        accuracy: 40,
        bulletSpeed: 62,
        mobility: 94
    },
    {
        name: "M16S",
        ammo: 30, magazines: 5,
        duration: "30 Days",
        price: 49.00,
        image: "src/imagens/rifles/m16s.png",
        damage: 76,
        rateOfFire: 70,
        range: 66,
        accuracy: 50,
        bulletSpeed: 66,
        mobility: 95
    },
    {
        name: "F2000 Antitank",
        ammo: 30, magazines: 5,
        duration: "Permanent",
        price: 188.00,
        image: "src/imagens/rifles/f2000.png",
        damage: 70,
        rateOfFire: 80,
        range: 74,
        accuracy: 80,
        bulletSpeed: 74,
        mobility: 94
    },
    {
        name: "M16",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 168.00,
        image: "src/imagens/rifles/m16.png",
        damage: 70,
        rateOfFire: 78,
        range: 80,
        accuracy: 82,
        bulletSpeed: 78,
        mobility: 94
    },
    {
        name: "G36K",
        ammo: 30, magazines: 5,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/rifles/g36k.png",
        damage: 71,
        rateOfFire: 70,
        range: 71,
        accuracy: 74,
        bulletSpeed: 75,
        mobility: 94
    },
    {
        name: "M4-GL",
        ammo: 30, magazines: 6,
        duration: "Permanent",
        price: 128.00,
        image: "src/imagens/rifles/m4_gl.png",
        damage: 70,
        rateOfFire: 70,
        range: 90,
        accuracy: 77,
        bulletSpeed: 72,
        mobility: 94
    },
    {
        name: "Scar Custom",
        ammo: 30, magazines: 5,
        duration: "30 Days",
        price: 65.00,
        image: "src/imagens/rifles/scar_custom.png",
        damage: 75,
        rateOfFire: 70,
        range: 80,
        accuracy: 81,
        bulletSpeed: 78,
        mobility: 94
    },
];
