const snipers = [
  {
    name: "Mini14",
    ammo: 7, magazines: 4,
    duration: "Permanent",
    price: 265.00,
    image: "src/imagens/snipers/mini14.png",
    damage: 49,
    rateOfFire: 240,
    range: 65,
    accuracy: 78,
    bulletSpeed: 80,
    mobility: 90
  },
  {
    name: "M24S (Deep Purple)",
    ammo: 10, magazines: 4,
    duration: "Permanent",
    price: 168.00,
    image: "src/imagens/snipers/m24s_purple.png",
    damage: 89,
    rateOfFire: 60,
    range: 69,
    accuracy: 78,
    bulletSpeed: 76,
    mobility: 90
  },
  {
    name: "AWP (Wood)",
    ammo: 10, magazines: 4,
    duration: "Permanent",
    price: 168.00,
    image: "src/imagens/snipers/awp_wood.png",
    damage: 79,
    rateOfFire: 70,
    range: 80,
    accuracy: 64,
    bulletSpeed: 86,
    mobility: 90
  },
  {
    name: "AWP (Golden Dragon)",
    ammo: 10, magazines: 4,
    duration: "Permanent",
    price: 168.00,
    image: "src/imagens/snipers/awp_golden.png",
    damage: 79,
    rateOfFire: 70,
    range: 80,
    accuracy: 64,
    bulletSpeed: 86,
    mobility: 90
  },
  {
    name: "Scar21 (Bate)",
    ammo: 7, magazines: 3,
    duration: "Permanent",
    price: 256.00,
    image: "src/imagens/snipers/scar21.png",
    damage: 55,
    rateOfFire: 235,
    range: 70,
    accuracy: 70,
    bulletSpeed: 70,
    mobility: 80
  },
  {
    name: "HK417",
    ammo: 10, magazines: 4,
    duration: "Permanent",
    price: 256.00,
    image: "src/imagens/snipers/hk417.png",
    damage: 91,
    rateOfFire: 68,
    range: 69,
    accuracy: 78,
    bulletSpeed: 74,
    mobility: 90
  },
  {
    name: "U88",
    ammo: 10, magazines: 4,
    duration: "Permanent",
    price: 188.00,
    image: "src/imagens/snipers/u88.png",
    damage: 88,
    rateOfFire: 65,
    range: 78,
    accuracy: 80,
    bulletSpeed: 75,
    mobility: 90
  },
  {
    name: "AWP",
    ammo: 10, magazines: 4,
    duration: "Permanent",
    price: 128.00,
    image: "src/imagens/snipers/awp.png",
    damage: 79,
    rateOfFire: 70,
    range: 80,
    accuracy: 64,
    bulletSpeed: 86,
    mobility: 90
  },
  {
    name: "SR25",
    ammo: 10, magazines: 5,
    duration: "Permanent",
    price: 118.00,
    image: "src/imagens/snipers/sr25.png",
    damage: 77,
    rateOfFire: 70,
    range: 63,
    accuracy: 70,
    bulletSpeed: 78,
    mobility: 90
  },
  {
    name: "SG3000",
    ammo: 10, magazines: 5,
    duration: "Permanent",
    price: 288.00,
    image: "src/imagens/snipers/sg3000.png",
    damage: 89,
    rateOfFire: 60,
    range: 67,
    accuracy: 80,
    bulletSpeed: 74,
    mobility: 90
  },
  {
    name: "L115A3",
    ammo: 10, magazines: 5,
    duration: "Permanent",
    price: 168.00,
    image: "src/imagens/snipers/l115a3.png",
    damage: 76,
    rateOfFire: 61,
    range: 86,
    accuracy: 80,
    bulletSpeed: 70,
    mobility: 90
  },
  {
    name: "M40A3",
    ammo: 10, magazines: 5,
    duration: "Permanent",
    price: 128.00,
    image: "src/imagens/snipers/m40a3.png",
    damage: 70,
    rateOfFire: 70,
    range: 82,
    accuracy: 80,
    bulletSpeed: 79,
    mobility: 90
  },
  {
    name: "M95-SS (Tradeable)",
    ammo: 5, magazines: 4,
    duration: "Permanent",
    price: "Lottery - Limited",
    image: "src/imagens/snipers/m95_ss.png",
    damage: 91,
    rateOfFire: 70,
    range: 81,
    accuracy: 75,
    bulletSpeed: 75,
    mobility: 90
  }
];
